// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Provenance of a build. Contains all information needed to verify the full
/// details about the build from source to completion.
public struct BuildProvenance: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Unique identifier of the build.
  public var id: Swift.String = Swift.String()

  /// ID of the project.
  public var projectId: Swift.String = Swift.String()

  /// Commands requested by the build.
  public var commands: [Command] = []

  /// Output of the build.
  public var builtArtifacts: [Artifact] = []

  /// Time at which the build was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Time at which execution of the build was started.
  public var startTime: GoogleCloudWkt.Timestamp? = nil

  /// Time at which execution of the build was finished.
  public var endTime: GoogleCloudWkt.Timestamp? = nil

  /// E-mail address of the user who initiated this build. Note that this was the
  /// user's e-mail address at the time the build was initiated; this address may
  /// not represent the same end-user for all time.
  public var creator: Swift.String = Swift.String()

  /// URI where any logs for this provenance were written.
  public var logsUri: Swift.String = Swift.String()

  /// Details of the Source input to the build.
  public var sourceProvenance: Source? = nil

  /// Trigger identifier if the build was triggered automatically; empty if not.
  public var triggerId: Swift.String = Swift.String()

  /// Special options applied to this build. This is a catch-all field where
  /// build providers can enter any desired additional details.
  public var buildOptions: [Swift.String: Swift.String] = [:]

  /// Version string of the builder at the time this build was executed.
  public var builderVersion: Swift.String = Swift.String()

  /// Initialize a new instance of `BuildProvenance`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BuildProvenance().with { $0.id = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: String { return "type.googleapis.com/grafeas.v1.BuildProvenance" }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
