// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Indicates that the builder claims certain fields in this message to be
/// complete.
public struct Completeness: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// If true, the builder claims that recipe.arguments is complete, meaning that
  /// all external inputs are properly captured in the recipe.
  public var arguments: Swift.Bool = Swift.Bool()

  /// If true, the builder claims that recipe.environment is claimed to be
  /// complete.
  public var environment: Swift.Bool = Swift.Bool()

  /// If true, the builder claims that materials are complete, usually through
  /// some controls to prevent network access. Sometimes called "hermetic".
  public var materials: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `Completeness`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Completeness().with { $0.arguments = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/grafeas.v1.Completeness"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
