// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Describes the CIS benchmark version that is applicable to a given OS and
/// os version.
public struct ComplianceVersion: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The CPE URI (https://cpe.mitre.org/specification/) this benchmark is
  /// applicable to.
  public var cpeUri: Swift.String = Swift.String()

  /// The name of the document that defines this benchmark, e.g. "CIS
  /// Container-Optimized OS".
  public var benchmarkDocument: Swift.String = Swift.String()

  /// The version of the benchmark. This is set to the version of the OS-specific
  /// CIS document the benchmark is defined in.
  public var version: Swift.String = Swift.String()

  /// Initialize a new instance of `ComplianceVersion`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ComplianceVersion().with { $0.cpeUri = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/grafeas.v1.ComplianceVersion"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
