// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The period during which some deployable was active in a runtime.
public struct DeploymentOccurrence: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Identity of the user that triggered this deployment.
  public var userEmail: Swift.String = Swift.String()

  /// Required. Beginning of the lifetime of this deployment.
  public var deployTime: GoogleCloudWKT.Timestamp? = nil

  /// End of the lifetime of this deployment.
  public var undeployTime: GoogleCloudWKT.Timestamp? = nil

  /// Configuration used to create this deployment.
  public var config: Swift.String = Swift.String()

  /// Address of the runtime element hosting this deployment.
  public var address: Swift.String = Swift.String()

  /// Output only. Resource URI for the artifact being deployed taken from
  /// the deployable field with the same name.
  public var resourceUri: [Swift.String] = []

  /// Platform hosting this deployment.
  public var platform: DeploymentOccurrence.Platform = DeploymentOccurrence.Platform()

  /// Initialize a new instance of `DeploymentOccurrence`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DeploymentOccurrence().with { $0.userEmail = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Types of platforms.
  public enum Platform: Codable, Equatable, Sendable {
    /// Unknown.
    case unspecified
    /// Google Container Engine.
    case gke
    /// Google App Engine: Flexible Environment.
    case flex
    /// Custom user-defined platform.
    case custom
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .gke: return 1
      case .flex: return 2
      case .custom: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "PLATFORM_UNSPECIFIED"
      case .gke: return "GKE"
      case .flex: return "FLEX"
      case .custom: return "CUSTOM"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Platform/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "PLATFORM_UNSPECIFIED": self = .unspecified
      case "GKE": self = .gke
      case "FLEX": self = .flex
      case "CUSTOM": self = .custom
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Platform/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .gke
      case 2: self = .flex
      case 3: self = .custom
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .gke: return try container.encode(1)
      case .flex: return try container.encode(2)
      case .custom: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/grafeas.v1.DeploymentOccurrence"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
