// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt
import GoogleRpc

/// Provides information about the analysis status of a discovered resource.
public struct DiscoveryOccurrence: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Whether the resource is continuously analyzed.
  public var continuousAnalysis: DiscoveryOccurrence.ContinuousAnalysis =
    DiscoveryOccurrence.ContinuousAnalysis()

  /// The status of discovery for the resource.
  public var analysisStatus: DiscoveryOccurrence.AnalysisStatus =
    DiscoveryOccurrence.AnalysisStatus()

  public var analysisCompleted: DiscoveryOccurrence.AnalysisCompleted? = nil

  /// Indicates any errors encountered during analysis of a resource. There
  /// could be 0 or more of these errors.
  public var analysisError: [GoogleRpc.Status] = []

  /// When an error is encountered this will contain a LocalizedMessage under
  /// details to show to the user. The LocalizedMessage is output only and
  /// populated by the API.
  public var analysisStatusError: GoogleRpc.Status? = nil

  /// The CPE of the resource being scanned.
  public var cpe: Swift.String = Swift.String()

  /// The last time this resource was scanned.
  public var lastScanTime: GoogleCloudWkt.Timestamp? = nil

  /// The time occurrences related to this discovery occurrence were archived.
  public var archiveTime: GoogleCloudWkt.Timestamp? = nil

  /// The status of an SBOM generation.
  public var sbomStatus: DiscoveryOccurrence.SBOMStatus? = nil

  /// The status of an vulnerability attestation generation.
  public var vulnerabilityAttestation: DiscoveryOccurrence.VulnerabilityAttestation? = nil

  /// Files that make up the resource described by the occurrence.
  public var files: [DiscoveryOccurrence.File] = []

  /// The last time vulnerability scan results changed.
  public var lastVulnerabilityUpdateTime: GoogleCloudWkt.Timestamp? = nil

  /// Initialize a new instance of `DiscoveryOccurrence`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DiscoveryOccurrence().with { $0.continuousAnalysis = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Indicates which analysis completed successfully. Multiple types of
  /// analysis can be performed on a single resource.
  public struct AnalysisCompleted: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    public var analysisType: [Swift.String] = []

    /// Initialize a new instance of `AnalysisCompleted`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = AnalysisCompleted().with { $0.analysisType = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/grafeas.v1.DiscoveryOccurrence.AnalysisCompleted"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// The status of an SBOM generation.
  public struct SBOMStatus: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The progress of the SBOM generation.
    public var sbomState: DiscoveryOccurrence.SBOMStatus.SBOMState = DiscoveryOccurrence.SBOMStatus
      .SBOMState()

    /// If there was an error generating an SBOM, this will indicate what that
    /// error was.
    public var error: Swift.String = Swift.String()

    /// Initialize a new instance of `SBOMStatus`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SBOMStatus().with { $0.sbomState = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// An enum indicating the progress of the SBOM generation.
    public enum SBOMState: Codable, Equatable, Sendable {
      /// Default unknown state.
      case unspecified
      /// SBOM scanning is pending.
      case pending
      /// SBOM scanning has completed.
      case complete
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .pending: return 1
        case .complete: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "SBOM_STATE_UNSPECIFIED"
        case .pending: return "PENDING"
        case .complete: return "COMPLETE"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "SBOM_STATE_UNSPECIFIED": self = .unspecified
        case "PENDING": self = .pending
        case "COMPLETE": self = .complete
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .pending
        case 2: self = .complete
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .pending: return try container.encode(1)
        case .complete: return try container.encode(2)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/grafeas.v1.DiscoveryOccurrence.SBOMStatus"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// The status of an vulnerability attestation generation.
  public struct VulnerabilityAttestation: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The last time we attempted to generate an attestation.
    public var lastAttemptTime: GoogleCloudWkt.Timestamp? = nil

    /// The success/failure state of the latest attestation attempt.
    public var state: DiscoveryOccurrence.VulnerabilityAttestation.VulnerabilityAttestationState =
      DiscoveryOccurrence.VulnerabilityAttestation.VulnerabilityAttestationState()

    /// If failure, the error reason for why the attestation generation failed.
    public var error: Swift.String = Swift.String()

    /// Initialize a new instance of `VulnerabilityAttestation`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = VulnerabilityAttestation().with { $0.lastAttemptTime = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// An enum indicating the state of the attestation generation.
    public enum VulnerabilityAttestationState: Codable, Equatable, Sendable {
      /// Default unknown state.
      case unspecified
      /// Attestation was successfully generated and stored.
      case success
      /// Attestation was unsuccessfully generated and stored.
      case failure
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .success: return 1
        case .failure: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "VULNERABILITY_ATTESTATION_STATE_UNSPECIFIED"
        case .success: return "SUCCESS"
        case .failure: return "FAILURE"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "VULNERABILITY_ATTESTATION_STATE_UNSPECIFIED": self = .unspecified
        case "SUCCESS": self = .success
        case "FAILURE": self = .failure
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .success
        case 2: self = .failure
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .success: return try container.encode(1)
        case .failure: return try container.encode(2)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/grafeas.v1.DiscoveryOccurrence.VulnerabilityAttestation"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public struct File: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    public var name: Swift.String = Swift.String()

    public var digest: [Swift.String: Swift.String] = [:]

    /// Initialize a new instance of `File`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = File().with { $0.name = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/grafeas.v1.DiscoveryOccurrence.File"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Whether the resource is continuously analyzed.
  public enum ContinuousAnalysis: Codable, Equatable, Sendable {
    /// Unknown.
    case unspecified
    /// The resource is continuously analyzed.
    case active
    /// The resource is ignored for continuous analysis.
    case inactive
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .active: return 1
      case .inactive: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "CONTINUOUS_ANALYSIS_UNSPECIFIED"
      case .active: return "ACTIVE"
      case .inactive: return "INACTIVE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "CONTINUOUS_ANALYSIS_UNSPECIFIED": self = .unspecified
      case "ACTIVE": self = .active
      case "INACTIVE": self = .inactive
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .active
      case 2: self = .inactive
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .active: return try container.encode(1)
      case .inactive: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Analysis status for a resource. Currently for initial analysis only (not
  /// updated in continuous analysis).
  public enum AnalysisStatus: Codable, Equatable, Sendable {
    /// Unknown.
    case unspecified
    /// Resource is known but no action has been taken yet.
    case pending
    /// Resource is being analyzed.
    case scanning
    /// Analysis has completed.
    case complete
    /// Analysis has finished unsuccessfully, the analysis itself is in a bad
    /// state.
    case finishedFailed
    /// The resource is known not to be supported.
    case finishedUnsupported
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .pending: return 1
      case .scanning: return 2
      case .complete: return 3
      case .finishedFailed: return 4
      case .finishedUnsupported: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "ANALYSIS_STATUS_UNSPECIFIED"
      case .pending: return "PENDING"
      case .scanning: return "SCANNING"
      case .complete: return "COMPLETE"
      case .finishedFailed: return "FINISHED_FAILED"
      case .finishedUnsupported: return "FINISHED_UNSUPPORTED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ANALYSIS_STATUS_UNSPECIFIED": self = .unspecified
      case "PENDING": self = .pending
      case "SCANNING": self = .scanning
      case "FINISHED_SUCCESS": self = .complete
      case "COMPLETE": self = .complete
      case "FINISHED_FAILED": self = .finishedFailed
      case "FINISHED_UNSUPPORTED": self = .finishedUnsupported
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .pending
      case 2: self = .scanning
      case 3: self = .complete
      case 4: self = .finishedFailed
      case 5: self = .finishedUnsupported
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .pending: return try container.encode(1)
      case .scanning: return try container.encode(2)
      case .complete: return try container.encode(3)
      case .finishedFailed: return try container.encode(4)
      case .finishedUnsupported: return try container.encode(5)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/grafeas.v1.DiscoveryOccurrence"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
