// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

public struct DSSEAttestationNote: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// DSSEHint hints at the purpose of the attestation authority.
  public var hint: DSSEAttestationNote.DSSEHint? = nil

  /// Initialize a new instance of `DSSEAttestationNote`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DSSEAttestationNote().with { $0.hint = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// This submessage provides human-readable hints about the purpose of the
  /// authority. Because the name of a note acts as its resource reference, it is
  /// important to disambiguate the canonical name of the Note (which might be a
  /// UUID for security purposes) from "readable" names more suitable for debug
  /// output. Note that these hints should not be used to look up authorities in
  /// security sensitive contexts, such as when looking up attestations to
  /// verify.
  public struct DSSEHint: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. The human readable name of this attestation authority, for
    /// example "cloudbuild-prod".
    public var humanReadableName: Swift.String = Swift.String()

    /// Initialize a new instance of `DSSEHint`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DSSEHint().with { $0.humanReadableName = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/grafeas.v1.DSSEAttestationNote.DSSEHint"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/grafeas.v1.DSSEAttestationNote"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
