// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Deprecated. Prefer to use a regular Occurrence, and populate the
/// Envelope at the top level of the Occurrence.
public struct DSSEAttestationOccurrence: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// If doing something security critical, make sure to verify the signatures in
  /// this metadata.
  public var envelope: Envelope? = nil

  public var decodedPayload: OneOf_DecodedPayload? = nil

  /// Initialize a new instance of `DSSEAttestationOccurrence`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DSSEAttestationOccurrence().with { $0.envelope = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case envelope = "envelope"
    case statement = "statement"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.envelope = try container.decodeIfPresent(Envelope.self, forKey: .envelope)

    var decodedPayload: OneOf_DecodedPayload? = nil
    let decodedPayloadCheckAndSet = {
      if decodedPayload != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'decodedPayload'"))
      }
      decodedPayload = $0
    }
    if let statement = try container.decodeIfPresent(InTotoStatement?.self, forKey: .statement) {
      try decodedPayloadCheckAndSet(.statement(statement))
    }
    self.decodedPayload = decodedPayload
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.envelope, forKey: .envelope)

    if let choice = self.decodedPayload {
      switch choice {
      case .statement(let value):
        try container.encode(value, forKey: .statement)
      }
    }
  }

  public enum OneOf_DecodedPayload: Codable, Equatable, Sendable {
    indirect case statement(InTotoStatement?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/grafeas.v1.DSSEAttestationOccurrence"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
