// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Indicates the location at which a package was found.
public struct FileLocation: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// For jars that are contained inside .war files, this filepath
  /// can indicate the path to war file combined with the path to jar file.
  public var filePath: Swift.String = Swift.String()

  /// Each package found in a file should have its own layer metadata (that is,
  /// information from the origin layer of the package).
  public var layerDetails: LayerDetails? = nil

  /// Line number in the file where the package was found.
  /// Optional field that only applies to source repository scanning.
  public var lineNumber: Swift.Int32 = Swift.Int32()

  /// Initialize a new instance of `FileLocation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = FileLocation().with { $0.filePath = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/grafeas.v1.FileLocation"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
