// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A SourceContext referring to a Gerrit project.
public struct GerritSourceContext: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The URI of a running Gerrit instance.
  public var hostUri: Swift.String = Swift.String()

  /// The full project name within the host. Projects may be nested, so
  /// "project/subproject" is a valid project name. The "repo name" is the
  /// hostURI/project.
  public var gerritProject: Swift.String = Swift.String()

  /// A revision in a Gerrit project can be identified by either its revision ID
  /// or its alias.
  public var revision: OneOf_Revision? = nil

  /// Initialize a new instance of `GerritSourceContext`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GerritSourceContext().with { $0.hostUri = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case hostUri = "hostUri"
    case gerritProject = "gerritProject"
    case revisionId = "revisionId"
    case aliasContext = "aliasContext"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.hostUri = try container.decode(Swift.String.self, forKey: .hostUri)
    self.gerritProject = try container.decode(Swift.String.self, forKey: .gerritProject)

    var revision: OneOf_Revision? = nil
    let revisionCheckAndSet = {
      if revision != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'revision'"))
      }
      revision = $0
    }
    if let revisionId = try container.decodeIfPresent(Swift.String.self, forKey: .revisionId) {
      try revisionCheckAndSet(.revisionId(revisionId))
    }
    if let aliasContext = try container.decodeIfPresent(AliasContext?.self, forKey: .aliasContext) {
      try revisionCheckAndSet(.aliasContext(aliasContext))
    }
    self.revision = revision
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.hostUri, forKey: .hostUri)
    try container.encode(self.gerritProject, forKey: .gerritProject)

    if let choice = self.revision {
      switch choice {
      case .revisionId(let value):
        try container.encode(value, forKey: .revisionId)
      case .aliasContext(let value):
        try container.encode(value, forKey: .aliasContext)
      }
    }
  }

  /// A revision in a Gerrit project can be identified by either its revision ID
  /// or its alias.
  public enum OneOf_Revision: Codable, Equatable, Sendable {
    /// A revision (commit) ID.
    case revisionId(Swift.String)
    /// An alias, which may be a branch or tag.
    indirect case aliasContext(AliasContext?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/grafeas.v1.GerritSourceContext"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
