// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWKT
@_spi(GoogleCloudInternal) import GoogleCloudGax

extension Clients {
  final class GrafeasTransport: GrafeasStub {
    let inner: GoogleCloudGax._HTTPClient

    public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
      self.inner = try GoogleCloudGax._HTTPClient(
        from: options,
        withDefaultEndpoint: "https://containeranalysis.googleapis.com",
      )
    }

    public func getOccurrence(
      request: GetOccurrenceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.Occurrence {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/occurrences/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/occurrences/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/occurrences/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/occurrences/*"
          )
          paths.append(builder.build())
        }
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/occurrences/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/occurrences/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleGrafeasV1.Occurrence.self, timeout: options.attemptTimeout
      ).get()
    }

    public func listOccurrences(
      request: ListOccurrencesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.ListOccurrencesResponse {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.parent as Swift.String?,
              matching: [.literal("projects/"), .singleWildcard],
              fieldName: "parent")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/occurrences"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleCloudGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
          query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
          query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
          query.append(
            contentsOf: try encoder.encode(
              request.returnPartialSuccess, prefix: "returnPartialSuccess"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.parent as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              ],
              fieldName: "parent")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/occurrences"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleCloudGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
          query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
          query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
          query.append(
            contentsOf: try encoder.encode(
              request.returnPartialSuccess, prefix: "returnPartialSuccess"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [.literal("projects/"), .singleWildcard],
            fieldName: "parent",
            expecting: "projects/*"
          )
          paths.append(builder.build())
        }
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
            ],
            fieldName: "parent",
            expecting: "projects/*/locations/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleGrafeasV1.ListOccurrencesResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func deleteOccurrence(
      request: DeleteOccurrenceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/occurrences/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.DELETE) })
        }
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/occurrences/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.DELETE) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/occurrences/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/occurrences/*"
          )
          paths.append(builder.build())
        }
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/occurrences/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/occurrences/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      _ = try await req.rpc(
        GoogleCloudWKT.Empty.self, timeout: options.attemptTimeout
      ).get()
    }

    public func createOccurrence(
      request: CreateOccurrenceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.Occurrence {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.parent as Swift.String?,
              matching: [.literal("projects/"), .singleWildcard],
              fieldName: "parent")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/occurrences"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) })
        }
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.parent as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              ],
              fieldName: "parent")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/occurrences"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [.literal("projects/"), .singleWildcard],
            fieldName: "parent",
            expecting: "projects/*"
          )
          paths.append(builder.build())
        }
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
            ],
            fieldName: "parent",
            expecting: "projects/*/locations/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.occurrence {
        try req.setBody(json: body)
      }
      return try await req.rpc(
        GoogleGrafeasV1.Occurrence.self, timeout: options.attemptTimeout
      ).get()
    }

    public func batchCreateOccurrences(
      request: BatchCreateOccurrencesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.BatchCreateOccurrencesResponse {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.parent as Swift.String?,
              matching: [.literal("projects/"), .singleWildcard],
              fieldName: "parent")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/occurrences:batchCreate"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) })
        }
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.parent as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              ],
              fieldName: "parent")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/occurrences:batchCreate"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [.literal("projects/"), .singleWildcard],
            fieldName: "parent",
            expecting: "projects/*"
          )
          paths.append(builder.build())
        }
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
            ],
            fieldName: "parent",
            expecting: "projects/*/locations/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      try req.setBody(json: request)
      return try await req.rpc(
        GoogleGrafeasV1.BatchCreateOccurrencesResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func updateOccurrence(
      request: UpdateOccurrenceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.Occurrence {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/occurrences/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleCloudGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.updateMask, prefix: "updateMask"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.PATCH) })
        }
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/occurrences/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleCloudGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.updateMask, prefix: "updateMask"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.PATCH) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/occurrences/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/occurrences/*"
          )
          paths.append(builder.build())
        }
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/occurrences/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/occurrences/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.occurrence {
        try req.setBody(json: body)
      }
      return try await req.rpc(
        GoogleGrafeasV1.Occurrence.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getOccurrenceNote(
      request: GetOccurrenceNoteRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.Note {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/occurrences/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/notes"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/occurrences/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/notes"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/occurrences/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/occurrences/*"
          )
          paths.append(builder.build())
        }
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/occurrences/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/occurrences/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleGrafeasV1.Note.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getNote(
      request: GetNoteRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.Note {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/notes/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/notes/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/notes/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/notes/*"
          )
          paths.append(builder.build())
        }
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/notes/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/notes/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleGrafeasV1.Note.self, timeout: options.attemptTimeout
      ).get()
    }

    public func listNotes(
      request: ListNotesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.ListNotesResponse {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.parent as Swift.String?,
              matching: [.literal("projects/"), .singleWildcard],
              fieldName: "parent")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/notes"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleCloudGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
          query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
          query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
          query.append(
            contentsOf: try encoder.encode(
              request.returnPartialSuccess, prefix: "returnPartialSuccess"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.parent as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              ],
              fieldName: "parent")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/notes"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleCloudGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
          query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
          query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
          query.append(
            contentsOf: try encoder.encode(
              request.returnPartialSuccess, prefix: "returnPartialSuccess"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [.literal("projects/"), .singleWildcard],
            fieldName: "parent",
            expecting: "projects/*"
          )
          paths.append(builder.build())
        }
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
            ],
            fieldName: "parent",
            expecting: "projects/*/locations/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleGrafeasV1.ListNotesResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func deleteNote(
      request: DeleteNoteRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/notes/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.DELETE) })
        }
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/notes/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.DELETE) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/notes/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/notes/*"
          )
          paths.append(builder.build())
        }
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/notes/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/notes/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      _ = try await req.rpc(
        GoogleCloudWKT.Empty.self, timeout: options.attemptTimeout
      ).get()
    }

    public func createNote(
      request: CreateNoteRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.Note {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.parent as Swift.String?,
              matching: [.literal("projects/"), .singleWildcard],
              fieldName: "parent")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/notes"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleCloudGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.noteId, prefix: "noteId"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) })
        }
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.parent as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              ],
              fieldName: "parent")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/notes"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleCloudGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.noteId, prefix: "noteId"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [.literal("projects/"), .singleWildcard],
            fieldName: "parent",
            expecting: "projects/*"
          )
          paths.append(builder.build())
        }
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
            ],
            fieldName: "parent",
            expecting: "projects/*/locations/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.note {
        try req.setBody(json: body)
      }
      return try await req.rpc(
        GoogleGrafeasV1.Note.self, timeout: options.attemptTimeout
      ).get()
    }

    public func batchCreateNotes(
      request: BatchCreateNotesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.BatchCreateNotesResponse {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.parent as Swift.String?,
              matching: [.literal("projects/"), .singleWildcard],
              fieldName: "parent")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/notes:batchCreate"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) })
        }
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.parent as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              ],
              fieldName: "parent")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/notes:batchCreate"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [.literal("projects/"), .singleWildcard],
            fieldName: "parent",
            expecting: "projects/*"
          )
          paths.append(builder.build())
        }
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
            ],
            fieldName: "parent",
            expecting: "projects/*/locations/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      try req.setBody(json: request)
      return try await req.rpc(
        GoogleGrafeasV1.BatchCreateNotesResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func updateNote(
      request: UpdateNoteRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.Note {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/notes/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleCloudGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.updateMask, prefix: "updateMask"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.PATCH) })
        }
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/notes/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleCloudGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.updateMask, prefix: "updateMask"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.PATCH) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/notes/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/notes/*"
          )
          paths.append(builder.build())
        }
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/notes/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/notes/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.note {
        try req.setBody(json: body)
      }
      return try await req.rpc(
        GoogleGrafeasV1.Note.self, timeout: options.attemptTimeout
      ).get()
    }

    public func listNoteOccurrences(
      request: ListNoteOccurrencesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.ListNoteOccurrencesResponse {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/notes/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/occurrences"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleCloudGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
          query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
          query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/notes/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/occurrences"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleCloudGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
          query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
          query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/notes/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/notes/*"
          )
          paths.append(builder.build())
        }
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/notes/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/notes/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleGrafeasV1.ListNoteOccurrencesResponse.self, timeout: options.attemptTimeout
      ).get()
    }
  }
}
