// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleWKT
import GoogleGax

extension Clients {
  protocol GrafeasStub: Sendable {
    func getOccurrence(
      request: GetOccurrenceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.Occurrence

    func listOccurrences(
      request: ListOccurrencesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.ListOccurrencesResponse

    func deleteOccurrence(
      request: DeleteOccurrenceRequest, options: GoogleGax.RequestOptions
    ) async throws

    func createOccurrence(
      request: CreateOccurrenceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.Occurrence

    func batchCreateOccurrences(
      request: BatchCreateOccurrencesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.BatchCreateOccurrencesResponse

    func updateOccurrence(
      request: UpdateOccurrenceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.Occurrence

    func getOccurrenceNote(
      request: GetOccurrenceNoteRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.Note

    func getNote(
      request: GetNoteRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.Note

    func listNotes(
      request: ListNotesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.ListNotesResponse

    func deleteNote(
      request: DeleteNoteRequest, options: GoogleGax.RequestOptions
    ) async throws

    func createNote(
      request: CreateNoteRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.Note

    func batchCreateNotes(
      request: BatchCreateNotesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.BatchCreateNotesResponse

    func updateNote(
      request: UpdateNoteRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.Note

    func listNoteOccurrences(
      request: ListNoteOccurrencesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.ListNoteOccurrencesResponse
  }
}
