// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class GrafeasLogging: GrafeasStub {
    let inner: any GrafeasStub
    let logger: Logger

    public init(_ inner: any GrafeasStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "grafeas-v1"
      logger[metadataKey: "gcp.client.service"] = "containeranalysis"
      logger[metadataKey: "gcp.experimental.swift.client"] = "Grafeas"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func getOccurrence(
      request: GetOccurrenceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.Occurrence {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOccurrence",
        action: {
          (r: GetOccurrenceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleGrafeasV1.Occurrence
          in
          return try await self.inner.getOccurrence(request: r, options: o)
        })
    }

    public func listOccurrences(
      request: ListOccurrencesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.ListOccurrencesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOccurrences",
        action: {
          (r: ListOccurrencesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleGrafeasV1.ListOccurrencesResponse
          in
          return try await self.inner.listOccurrences(request: r, options: o)
        })
    }

    public func deleteOccurrence(
      request: DeleteOccurrenceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteOccurrence",
        action: {
          (r: DeleteOccurrenceRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteOccurrence(request: r, options: o)
        })
    }

    public func createOccurrence(
      request: CreateOccurrenceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.Occurrence {
      try await self._intercept(
        request: request,
        options: options,
        name: "createOccurrence",
        action: {
          (r: CreateOccurrenceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleGrafeasV1.Occurrence
          in
          return try await self.inner.createOccurrence(request: r, options: o)
        })
    }

    public func batchCreateOccurrences(
      request: BatchCreateOccurrencesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.BatchCreateOccurrencesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "batchCreateOccurrences",
        action: {
          (r: BatchCreateOccurrencesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleGrafeasV1.BatchCreateOccurrencesResponse
          in
          return try await self.inner.batchCreateOccurrences(request: r, options: o)
        })
    }

    public func updateOccurrence(
      request: UpdateOccurrenceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.Occurrence {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateOccurrence",
        action: {
          (r: UpdateOccurrenceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleGrafeasV1.Occurrence
          in
          return try await self.inner.updateOccurrence(request: r, options: o)
        })
    }

    public func getOccurrenceNote(
      request: GetOccurrenceNoteRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.Note {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOccurrenceNote",
        action: {
          (r: GetOccurrenceNoteRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleGrafeasV1.Note
          in
          return try await self.inner.getOccurrenceNote(request: r, options: o)
        })
    }

    public func getNote(
      request: GetNoteRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.Note {
      try await self._intercept(
        request: request,
        options: options,
        name: "getNote",
        action: {
          (r: GetNoteRequest, o: GoogleCloudGax.RequestOptions) async throws -> GoogleGrafeasV1.Note
          in
          return try await self.inner.getNote(request: r, options: o)
        })
    }

    public func listNotes(
      request: ListNotesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.ListNotesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listNotes",
        action: {
          (r: ListNotesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleGrafeasV1.ListNotesResponse
          in
          return try await self.inner.listNotes(request: r, options: o)
        })
    }

    public func deleteNote(
      request: DeleteNoteRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteNote",
        action: { (r: DeleteNoteRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteNote(request: r, options: o)
        })
    }

    public func createNote(
      request: CreateNoteRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.Note {
      try await self._intercept(
        request: request,
        options: options,
        name: "createNote",
        action: {
          (r: CreateNoteRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleGrafeasV1.Note
          in
          return try await self.inner.createNote(request: r, options: o)
        })
    }

    public func batchCreateNotes(
      request: BatchCreateNotesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.BatchCreateNotesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "batchCreateNotes",
        action: {
          (r: BatchCreateNotesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleGrafeasV1.BatchCreateNotesResponse
          in
          return try await self.inner.batchCreateNotes(request: r, options: o)
        })
    }

    public func updateNote(
      request: UpdateNoteRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.Note {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateNote",
        action: {
          (r: UpdateNoteRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleGrafeasV1.Note
          in
          return try await self.inner.updateNote(request: r, options: o)
        })
    }

    public func listNoteOccurrences(
      request: ListNoteOccurrencesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.ListNoteOccurrencesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listNoteOccurrences",
        action: {
          (r: ListNoteOccurrencesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleGrafeasV1.ListNoteOccurrencesResponse
          in
          return try await self.inner.listNoteOccurrences(request: r, options: o)
        })
    }
  }
}
