// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax

extension Clients {
  final class GrafeasRetry: GrafeasStub {
    let inner: any GrafeasStub
    let options: GoogleCloudGax.ClientOptions

    public init(_ inner: any GrafeasStub, options: GoogleCloudGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleCloudGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func getOccurrence(
      request: GetOccurrenceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.Occurrence {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetOccurrenceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleGrafeasV1.Occurrence
          in
          return try await self.inner.getOccurrence(request: r, options: o)
        })
    }

    public func listOccurrences(
      request: ListOccurrencesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.ListOccurrencesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListOccurrencesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleGrafeasV1.ListOccurrencesResponse
          in
          return try await self.inner.listOccurrences(request: r, options: o)
        })
    }

    public func deleteOccurrence(
      request: DeleteOccurrenceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteOccurrenceRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteOccurrence(request: r, options: o)
        })
    }

    public func createOccurrence(
      request: CreateOccurrenceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.Occurrence {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateOccurrenceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleGrafeasV1.Occurrence
          in
          return try await self.inner.createOccurrence(request: r, options: o)
        })
    }

    public func batchCreateOccurrences(
      request: BatchCreateOccurrencesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.BatchCreateOccurrencesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: BatchCreateOccurrencesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleGrafeasV1.BatchCreateOccurrencesResponse
          in
          return try await self.inner.batchCreateOccurrences(request: r, options: o)
        })
    }

    public func updateOccurrence(
      request: UpdateOccurrenceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.Occurrence {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateOccurrenceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleGrafeasV1.Occurrence
          in
          return try await self.inner.updateOccurrence(request: r, options: o)
        })
    }

    public func getOccurrenceNote(
      request: GetOccurrenceNoteRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.Note {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetOccurrenceNoteRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleGrafeasV1.Note
          in
          return try await self.inner.getOccurrenceNote(request: r, options: o)
        })
    }

    public func getNote(
      request: GetNoteRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.Note {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetNoteRequest, o: GoogleCloudGax.RequestOptions) async throws -> GoogleGrafeasV1.Note
          in
          return try await self.inner.getNote(request: r, options: o)
        })
    }

    public func listNotes(
      request: ListNotesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.ListNotesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListNotesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleGrafeasV1.ListNotesResponse
          in
          return try await self.inner.listNotes(request: r, options: o)
        })
    }

    public func deleteNote(
      request: DeleteNoteRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: { (r: DeleteNoteRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteNote(request: r, options: o)
        })
    }

    public func createNote(
      request: CreateNoteRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.Note {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateNoteRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleGrafeasV1.Note
          in
          return try await self.inner.createNote(request: r, options: o)
        })
    }

    public func batchCreateNotes(
      request: BatchCreateNotesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.BatchCreateNotesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: BatchCreateNotesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleGrafeasV1.BatchCreateNotesResponse
          in
          return try await self.inner.batchCreateNotes(request: r, options: o)
        })
    }

    public func updateNote(
      request: UpdateNoteRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.Note {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateNoteRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleGrafeasV1.Note
          in
          return try await self.inner.updateNote(request: r, options: o)
        })
    }

    public func listNoteOccurrences(
      request: ListNoteOccurrencesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleGrafeasV1.ListNoteOccurrencesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListNoteOccurrencesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleGrafeasV1.ListNoteOccurrencesResponse
          in
          return try await self.inner.listNoteOccurrences(request: r, options: o)
        })
    }
  }
}
