// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

public struct InTotoProvenance: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  public var builderConfig: BuilderConfig? = nil

  /// Identifies the configuration used for the build.
  /// When combined with materials, this SHOULD fully describe the build,
  /// such that re-running this recipe results in bit-for-bit identical output
  /// (if the build is reproducible).
  public var recipe: Recipe? = nil

  public var metadata: Metadata? = nil

  /// The collection of artifacts that influenced the build including sources,
  /// dependencies, build tools, base images, and so on. This is considered to be
  /// incomplete unless metadata.completeness.materials is true. Unset or null is
  /// equivalent to empty.
  public var materials: [Swift.String] = []

  /// Initialize a new instance of `InTotoProvenance`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = InTotoProvenance().with { $0.builderConfig = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: String { return "type.googleapis.com/grafeas.v1.InTotoProvenance" }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
