// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Spec defined at
/// https://github.com/in-toto/attestation/tree/main/spec#statement The
/// serialized InTotoStatement will be stored as Envelope.payload.
/// Envelope.payloadType is always "application/vnd.in-toto+json".
public struct InTotoStatement: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Always `https://in-toto.io/Statement/v0.1`.
  public var type: Swift.String = Swift.String()

  public var subject: [Subject] = []

  /// `https://slsa.dev/provenance/v0.1` for SlsaProvenance.
  public var predicateType: Swift.String = Swift.String()

  public var predicate: OneOf_Predicate? = nil

  /// Initialize a new instance of `InTotoStatement`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = InTotoStatement().with { $0.type = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case type = "_type"
    case subject = "subject"
    case predicateType = "predicateType"
    case provenance = "provenance"
    case slsaProvenance = "slsaProvenance"
    case slsaProvenanceZeroTwo = "slsaProvenanceZeroTwo"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.type = try container.decode(Swift.String.self, forKey: .type)
    self.subject = try container.decode([Subject].self, forKey: .subject)
    self.predicateType = try container.decode(Swift.String.self, forKey: .predicateType)

    var predicate: OneOf_Predicate? = nil
    let predicateCheckAndSet = {
      if predicate != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'predicate'"))
      }
      predicate = $0
    }
    if let provenance = try container.decodeIfPresent(InTotoProvenance?.self, forKey: .provenance) {
      try predicateCheckAndSet(.provenance(provenance))
    }
    if let slsaProvenance = try container.decodeIfPresent(
      SlsaProvenance?.self, forKey: .slsaProvenance)
    {
      try predicateCheckAndSet(.slsaProvenance(slsaProvenance))
    }
    if let slsaProvenanceZeroTwo = try container.decodeIfPresent(
      SlsaProvenanceZeroTwo?.self, forKey: .slsaProvenanceZeroTwo)
    {
      try predicateCheckAndSet(.slsaProvenanceZeroTwo(slsaProvenanceZeroTwo))
    }
    self.predicate = predicate
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.type, forKey: .type)
    try container.encode(self.subject, forKey: .subject)
    try container.encode(self.predicateType, forKey: .predicateType)

    if let choice = self.predicate {
      switch choice {
      case .provenance(let value):
        try container.encode(value, forKey: .provenance)
      case .slsaProvenance(let value):
        try container.encode(value, forKey: .slsaProvenance)
      case .slsaProvenanceZeroTwo(let value):
        try container.encode(value, forKey: .slsaProvenanceZeroTwo)
      }
    }
  }

  public enum OneOf_Predicate: Codable, Equatable, Sendable {
    indirect case provenance(InTotoProvenance?)
    indirect case slsaProvenance(SlsaProvenance?)
    indirect case slsaProvenanceZeroTwo(SlsaProvenanceZeroTwo?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/grafeas.v1.InTotoStatement"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
