// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

public struct InTotoSlsaProvenanceV1: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// InToto spec defined at
  /// https://github.com/in-toto/attestation/tree/main/spec#statement
  public var type: Swift.String = Swift.String()

  public var subject: [Subject] = []

  public var predicateType: Swift.String = Swift.String()

  public var predicate: InTotoSlsaProvenanceV1.SlsaProvenanceV1? = nil

  /// Initialize a new instance of `InTotoSlsaProvenanceV1`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = InTotoSlsaProvenanceV1().with { $0.type = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case type = "_type"
    case subject = "subject"
    case predicateType = "predicateType"
    case predicate = "predicate"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.type = try container.decode(Swift.String.self, forKey: .type)
    self.subject = try container.decode([Subject].self, forKey: .subject)
    self.predicateType = try container.decode(Swift.String.self, forKey: .predicateType)
    self.predicate = try container.decodeIfPresent(
      InTotoSlsaProvenanceV1.SlsaProvenanceV1.self, forKey: .predicate)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.type, forKey: .type)
    try container.encode(self.subject, forKey: .subject)
    try container.encode(self.predicateType, forKey: .predicateType)
    try container.encode(self.predicate, forKey: .predicate)
  }

  /// Keep in sync with schema at
  /// https://github.com/slsa-framework/slsa/blob/main/docs/provenance/schema/v1/provenance.proto
  /// Builder renamed to ProvenanceBuilder because of Java conflicts.
  public struct SlsaProvenanceV1: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    public var buildDefinition: InTotoSlsaProvenanceV1.BuildDefinition? = nil

    public var runDetails: InTotoSlsaProvenanceV1.RunDetails? = nil

    /// Initialize a new instance of `SlsaProvenanceV1`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SlsaProvenanceV1().with { $0.buildDefinition = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/grafeas.v1.InTotoSlsaProvenanceV1.SlsaProvenanceV1"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public struct BuildDefinition: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    public var buildType: Swift.String = Swift.String()

    public var externalParameters: GoogleCloudWkt.Struct? = nil

    public var internalParameters: GoogleCloudWkt.Struct? = nil

    public var resolvedDependencies: [InTotoSlsaProvenanceV1.ResourceDescriptor] = []

    /// Initialize a new instance of `BuildDefinition`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = BuildDefinition().with { $0.buildType = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/grafeas.v1.InTotoSlsaProvenanceV1.BuildDefinition"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public struct ResourceDescriptor: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    public var name: Swift.String = Swift.String()

    public var uri: Swift.String = Swift.String()

    public var digest: [Swift.String: Swift.String] = [:]

    public var content: Foundation.Data = Foundation.Data()

    public var downloadLocation: Swift.String = Swift.String()

    public var mediaType: Swift.String = Swift.String()

    public var annotations: [Swift.String: GoogleCloudWkt.Value] = [:]

    /// Initialize a new instance of `ResourceDescriptor`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ResourceDescriptor().with { $0.name = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/grafeas.v1.InTotoSlsaProvenanceV1.ResourceDescriptor"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public struct RunDetails: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    public var builder: InTotoSlsaProvenanceV1.ProvenanceBuilder? = nil

    public var metadata: InTotoSlsaProvenanceV1.BuildMetadata? = nil

    public var byproducts: [InTotoSlsaProvenanceV1.ResourceDescriptor] = []

    /// Initialize a new instance of `RunDetails`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = RunDetails().with { $0.builder = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/grafeas.v1.InTotoSlsaProvenanceV1.RunDetails"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public struct ProvenanceBuilder: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    public var id: Swift.String = Swift.String()

    public var version: [Swift.String: Swift.String] = [:]

    public var builderDependencies: [InTotoSlsaProvenanceV1.ResourceDescriptor] = []

    /// Initialize a new instance of `ProvenanceBuilder`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ProvenanceBuilder().with { $0.id = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/grafeas.v1.InTotoSlsaProvenanceV1.ProvenanceBuilder"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public struct BuildMetadata: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    public var invocationId: Swift.String = Swift.String()

    public var startedOn: GoogleCloudWkt.Timestamp? = nil

    public var finishedOn: GoogleCloudWkt.Timestamp? = nil

    /// Initialize a new instance of `BuildMetadata`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = BuildMetadata().with { $0.invocationId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/grafeas.v1.InTotoSlsaProvenanceV1.BuildMetadata"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/grafeas.v1.InTotoSlsaProvenanceV1"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
