// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// License information.
public struct License: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Often a single license can be used to represent the licensing terms.
  /// Sometimes it is necessary to include a choice of one or more licenses
  /// or some combination of license identifiers.
  /// Examples: "LGPL-2.1-only OR MIT", "LGPL-2.1-only AND MIT",
  /// "GPL-2.0-or-later WITH Bison-exception-2.2".
  public var expression: Swift.String = Swift.String()

  /// Comments
  public var comments: Swift.String = Swift.String()

  /// Initialize a new instance of `License`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = License().with { $0.expression = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: String { return "type.googleapis.com/grafeas.v1.License" }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
