// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request to list occurrences.
public struct ListOccurrencesRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The name of the project to list occurrences for in the form of
  /// `projects/[PROJECT_ID]`.
  public var parent: Swift.String = Swift.String()

  /// The filter expression.
  public var filter: Swift.String = Swift.String()

  /// Number of occurrences to return in the list. Must be positive. Max allowed
  /// page size is 1000. If not specified, page size defaults to 20.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Token to provide to skip to a particular spot in the list.
  public var pageToken: Swift.String = Swift.String()

  /// If set, the request will return all reachable Occurrences
  /// and report all unreachable regions in the `unreachable` field in
  /// the response.
  ///
  /// Only applicable for requests in the global region.
  public var returnPartialSuccess: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `ListOccurrencesRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListOccurrencesRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/grafeas.v1.ListOccurrencesRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
