// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Other properties of the build.
public struct Metadata: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifies the particular build invocation, which can be useful for finding
  /// associated logs or other ad-hoc analysis. The value SHOULD be globally
  /// unique, per in-toto Provenance spec.
  public var buildInvocationId: Swift.String = Swift.String()

  /// The timestamp of when the build started.
  public var buildStartedOn: GoogleCloudWkt.Timestamp? = nil

  /// The timestamp of when the build completed.
  public var buildFinishedOn: GoogleCloudWkt.Timestamp? = nil

  /// Indicates that the builder claims certain fields in this message to be
  /// complete.
  public var completeness: Completeness? = nil

  /// If true, the builder claims that running the recipe on materials will
  /// produce bit-for-bit identical output.
  public var reproducible: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `Metadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Metadata().with { $0.buildInvocationId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: String { return "type.googleapis.com/grafeas.v1.Metadata" }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
