// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A type of analysis that can be done for a resource.
public struct Note: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The name of the note in the form of
  /// `projects/[PROVIDER_ID]/notes/[NOTE_ID]`.
  public var name: Swift.String = Swift.String()

  /// A one sentence description of this note.
  public var shortDescription: Swift.String = Swift.String()

  /// A detailed description of this note.
  public var longDescription: Swift.String = Swift.String()

  /// Output only. The type of analysis. This field can be used as a filter in
  /// list requests.
  public var kind: NoteKind = NoteKind()

  /// URLs associated with this note.
  public var relatedUrl: [RelatedUrl] = []

  /// Time of expiration for this note. Empty if note does not expire.
  public var expirationTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The time this note was created. This field can be used as a
  /// filter in list requests.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The time this note was last updated. This field can be used as
  /// a filter in list requests.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Other notes related to this note.
  public var relatedNoteNames: [Swift.String] = []

  /// Required. Immutable. The type of analysis this note represents.
  public var type: OneOf_Type? = nil

  /// Initialize a new instance of `Note`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Note().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case name = "name"
    case shortDescription = "shortDescription"
    case longDescription = "longDescription"
    case kind = "kind"
    case relatedUrl = "relatedUrl"
    case expirationTime = "expirationTime"
    case createTime = "createTime"
    case updateTime = "updateTime"
    case relatedNoteNames = "relatedNoteNames"
    case vulnerability = "vulnerability"
    case build = "build"
    case image = "image"
    case `package` = "package"
    case deployment = "deployment"
    case discovery = "discovery"
    case attestation = "attestation"
    case upgrade = "upgrade"
    case compliance = "compliance"
    case dsseAttestation = "dsseAttestation"
    case vulnerabilityAssessment = "vulnerabilityAssessment"
    case sbomReference = "sbomReference"
    case secret = "secret"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.shortDescription = try container.decode(Swift.String.self, forKey: .shortDescription)
    self.longDescription = try container.decode(Swift.String.self, forKey: .longDescription)
    self.kind = try container.decode(NoteKind.self, forKey: .kind)
    self.relatedUrl = try container.decode([RelatedUrl].self, forKey: .relatedUrl)
    self.expirationTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .expirationTime)
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .updateTime)
    self.relatedNoteNames = try container.decode([Swift.String].self, forKey: .relatedNoteNames)

    var type: OneOf_Type? = nil
    let typeCheckAndSet = {
      if type != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath, debugDescription: "Multiple values set for oneof 'type'"
          ))
      }
      type = $0
    }
    if let vulnerability = try container.decodeIfPresent(
      VulnerabilityNote?.self, forKey: .vulnerability)
    {
      try typeCheckAndSet(.vulnerability(vulnerability))
    }
    if let build = try container.decodeIfPresent(BuildNote?.self, forKey: .build) {
      try typeCheckAndSet(.build(build))
    }
    if let image = try container.decodeIfPresent(ImageNote?.self, forKey: .image) {
      try typeCheckAndSet(.image(image))
    }
    if let `package` = try container.decodeIfPresent(PackageNote?.self, forKey: .`package`) {
      try typeCheckAndSet(.`package`(`package`))
    }
    if let deployment = try container.decodeIfPresent(DeploymentNote?.self, forKey: .deployment) {
      try typeCheckAndSet(.deployment(deployment))
    }
    if let discovery = try container.decodeIfPresent(DiscoveryNote?.self, forKey: .discovery) {
      try typeCheckAndSet(.discovery(discovery))
    }
    if let attestation = try container.decodeIfPresent(AttestationNote?.self, forKey: .attestation)
    {
      try typeCheckAndSet(.attestation(attestation))
    }
    if let upgrade = try container.decodeIfPresent(UpgradeNote?.self, forKey: .upgrade) {
      try typeCheckAndSet(.upgrade(upgrade))
    }
    if let compliance = try container.decodeIfPresent(ComplianceNote?.self, forKey: .compliance) {
      try typeCheckAndSet(.compliance(compliance))
    }
    if let dsseAttestation = try container.decodeIfPresent(
      DSSEAttestationNote?.self, forKey: .dsseAttestation)
    {
      try typeCheckAndSet(.dsseAttestation(dsseAttestation))
    }
    if let vulnerabilityAssessment = try container.decodeIfPresent(
      VulnerabilityAssessmentNote?.self, forKey: .vulnerabilityAssessment)
    {
      try typeCheckAndSet(.vulnerabilityAssessment(vulnerabilityAssessment))
    }
    if let sbomReference = try container.decodeIfPresent(
      SBOMReferenceNote?.self, forKey: .sbomReference)
    {
      try typeCheckAndSet(.sbomReference(sbomReference))
    }
    if let secret = try container.decodeIfPresent(SecretNote?.self, forKey: .secret) {
      try typeCheckAndSet(.secret(secret))
    }
    self.type = type
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.shortDescription, forKey: .shortDescription)
    try container.encode(self.longDescription, forKey: .longDescription)
    try container.encode(self.kind, forKey: .kind)
    try container.encode(self.relatedUrl, forKey: .relatedUrl)
    try container.encode(self.expirationTime, forKey: .expirationTime)
    try container.encode(self.createTime, forKey: .createTime)
    try container.encode(self.updateTime, forKey: .updateTime)
    try container.encode(self.relatedNoteNames, forKey: .relatedNoteNames)

    if let choice = self.type {
      switch choice {
      case .vulnerability(let value):
        try container.encode(value, forKey: .vulnerability)
      case .build(let value):
        try container.encode(value, forKey: .build)
      case .image(let value):
        try container.encode(value, forKey: .image)
      case .`package`(let value):
        try container.encode(value, forKey: .`package`)
      case .deployment(let value):
        try container.encode(value, forKey: .deployment)
      case .discovery(let value):
        try container.encode(value, forKey: .discovery)
      case .attestation(let value):
        try container.encode(value, forKey: .attestation)
      case .upgrade(let value):
        try container.encode(value, forKey: .upgrade)
      case .compliance(let value):
        try container.encode(value, forKey: .compliance)
      case .dsseAttestation(let value):
        try container.encode(value, forKey: .dsseAttestation)
      case .vulnerabilityAssessment(let value):
        try container.encode(value, forKey: .vulnerabilityAssessment)
      case .sbomReference(let value):
        try container.encode(value, forKey: .sbomReference)
      case .secret(let value):
        try container.encode(value, forKey: .secret)
      }
    }
  }

  /// Required. Immutable. The type of analysis this note represents.
  public enum OneOf_Type: Codable, Equatable, Sendable {
    /// A note describing a package vulnerability.
    indirect case vulnerability(VulnerabilityNote?)
    /// A note describing build provenance for a verifiable build.
    indirect case build(BuildNote?)
    /// A note describing a base image.
    indirect case image(ImageNote?)
    /// A note describing a package hosted by various package managers.
    indirect case `package`(PackageNote?)
    /// A note describing something that can be deployed.
    indirect case deployment(DeploymentNote?)
    /// A note describing the initial analysis of a resource.
    indirect case discovery(DiscoveryNote?)
    /// A note describing an attestation role.
    indirect case attestation(AttestationNote?)
    /// A note describing available package upgrades.
    indirect case upgrade(UpgradeNote?)
    /// A note describing a compliance check.
    indirect case compliance(ComplianceNote?)
    /// A note describing a dsse attestation note.
    indirect case dsseAttestation(DSSEAttestationNote?)
    /// A note describing a vulnerability assessment.
    indirect case vulnerabilityAssessment(VulnerabilityAssessmentNote?)
    /// A note describing an SBOM reference.
    indirect case sbomReference(SBOMReferenceNote?)
    /// A note describing a secret.
    indirect case secret(SecretNote?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/grafeas.v1.Note"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
