// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Details on how a particular software package was installed on a system.
public struct PackageOccurrence: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The name of the installed package.
  public var name: Swift.String = Swift.String()

  /// All of the places within the filesystem versions of this package
  /// have been found.
  public var location: [Location] = []

  /// The type of package; whether native or non native (e.g., ruby gems,
  /// node.js packages, etc.).
  public var packageType: Swift.String = Swift.String()

  /// The cpe_uri in [CPE format](https://cpe.mitre.org/specification/)
  /// denoting the package manager version distributing a package.
  /// The cpe_uri will be blank for language packages.
  public var cpeUri: Swift.String = Swift.String()

  /// The CPU architecture for which packages in this distribution channel were
  /// built. Architecture will be blank for language packages.
  public var architecture: Architecture = Architecture()

  /// Licenses that have been declared by the authors of the package.
  public var license: License? = nil

  /// The version of the package.
  public var version: Version? = nil

  /// Initialize a new instance of `PackageOccurrence`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PackageOccurrence().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/grafeas.v1.PackageOccurrence"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
