// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// PackageNote represents a particular package version.
public struct PackageNote: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The name of the package.
  public var name: Swift.String = Swift.String()

  /// Deprecated.
  /// The various channels by which a package is distributed.
  public var distribution: [Distribution] = []

  /// The type of package; whether native or non native (e.g., ruby gems,
  /// node.js packages, etc.).
  public var packageType: Swift.String = Swift.String()

  /// The cpe_uri in [CPE format](https://cpe.mitre.org/specification/)
  /// denoting the package manager version distributing a package.
  /// The cpe_uri will be blank for language packages.
  public var cpeUri: Swift.String = Swift.String()

  /// The CPU architecture for which packages in this distribution channel were
  /// built. Architecture will be blank for language packages.
  public var architecture: Architecture = Architecture()

  /// The version of the package.
  public var version: Version? = nil

  /// A freeform text denoting the maintainer of this package.
  public var maintainer: Swift.String = Swift.String()

  /// The homepage for this package.
  public var url: Swift.String = Swift.String()

  /// The description of this package.
  public var description: Swift.String = Swift.String()

  /// Licenses that have been declared by the authors of the package.
  public var license: License? = nil

  /// Hash value, typically a file digest, that allows unique
  /// identification a specific package.
  public var digest: [Digest] = []

  /// Initialize a new instance of `PackageNote`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PackageNote().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/grafeas.v1.PackageNote"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
