// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// A predicate which describes the SBOM being referenced.
public struct SbomReferenceIntotoPredicate: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The person or system referring this predicate to the consumer.
  public var referrerId: Swift.String = Swift.String()

  /// The location of the SBOM.
  public var location: Swift.String = Swift.String()

  /// The mime type of the SBOM.
  public var mimeType: Swift.String = Swift.String()

  /// A map of algorithm to digest of the contents of the SBOM.
  public var digest: [Swift.String: Swift.String] = [:]

  /// Initialize a new instance of `SbomReferenceIntotoPredicate`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SbomReferenceIntotoPredicate().with { $0.referrerId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/grafeas.v1.SbomReferenceIntotoPredicate"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
