// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The actual payload that contains the SBOM Reference data.
/// The payload follows the intoto statement specification. See
/// https://github.com/in-toto/attestation/blob/main/spec/v1.0/statement.md
/// for more details.
public struct SbomReferenceIntotoPayload: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier for the schema of the Statement.
  public var type: Swift.String = Swift.String()

  /// URI identifying the type of the Predicate.
  public var predicateType: Swift.String = Swift.String()

  /// Set of software artifacts that the attestation applies to. Each element
  /// represents a single software artifact.
  public var subject: [Subject] = []

  /// Additional parameters of the Predicate. Includes the actual data about the
  /// SBOM.
  public var predicate: SbomReferenceIntotoPredicate? = nil

  /// Initialize a new instance of `SbomReferenceIntotoPayload`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SbomReferenceIntotoPayload().with { $0.type = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case type = "_type"
    case predicateType = "predicateType"
    case subject = "subject"
    case predicate = "predicate"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.type = try container.decode(Swift.String.self, forKey: .type)
    self.predicateType = try container.decode(Swift.String.self, forKey: .predicateType)
    self.subject = try container.decode([Subject].self, forKey: .subject)
    self.predicate = try container.decodeIfPresent(
      SbomReferenceIntotoPredicate.self, forKey: .predicate)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.type, forKey: .type)
    try container.encode(self.predicateType, forKey: .predicateType)
    try container.encode(self.subject, forKey: .subject)
    try container.encode(self.predicate, forKey: .predicate)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/grafeas.v1.SbomReferenceIntotoPayload"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
