// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The occurrence representing an SBOM reference as applied to a specific
/// resource. The occurrence follows the DSSE specification. See
/// https://github.com/secure-systems-lab/dsse/blob/master/envelope.md for more
/// details.
public struct SBOMReferenceOccurrence: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The actual payload that contains the SBOM reference data.
  public var payload: SbomReferenceIntotoPayload? = nil

  /// The kind of payload that SbomReferenceIntotoPayload takes. Since it's in
  /// the intoto format, this value is expected to be
  /// 'application/vnd.in-toto+json'.
  public var payloadType: Swift.String = Swift.String()

  /// The signatures over the payload.
  public var signatures: [EnvelopeSignature] = []

  /// Initialize a new instance of `SBOMReferenceOccurrence`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SBOMReferenceOccurrence().with { $0.payload = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/grafeas.v1.SBOMReferenceOccurrence"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
