// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// The location of the secret.
public struct SecretLocation: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The detailed location of the secret.
  public var location: OneOf_Location? = nil

  /// Initialize a new instance of `SecretLocation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SecretLocation().with { $0.fileLocation = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case fileLocation = "fileLocation"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var location: OneOf_Location? = nil
    let locationCheckAndSet = {
      if location != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'location'"))
      }
      location = $0
    }
    if let fileLocation = try container.decodeIfPresent(FileLocation?.self, forKey: .fileLocation) {
      try locationCheckAndSet(.fileLocation(fileLocation))
    }
    self.location = location
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.location {
      switch choice {
      case .fileLocation(let value):
        try container.encode(value, forKey: .fileLocation)
      }
    }
  }

  /// The detailed location of the secret.
  public enum OneOf_Location: Codable, Equatable, Sendable {
    /// The secret is found from a file.
    indirect case fileLocation(FileLocation?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/grafeas.v1.SecretLocation"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
