// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The occurrence provides details of a secret.
public struct SecretOccurrence: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Type of secret.
  public var kind: SecretKind = SecretKind()

  /// Locations where the secret is detected.
  public var locations: [SecretLocation] = []

  /// Status of the secret.
  public var statuses: [SecretStatus] = []

  /// Scan result of the secret.
  public var data: GoogleCloudWkt.`Any`? = nil

  /// Hash value, typically a digest for the secret data, that allows unique
  /// identification of a specific secret.
  public var digest: Digest? = nil

  /// Initialize a new instance of `SecretOccurrence`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SecretOccurrence().with { $0.kind = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: String { return "type.googleapis.com/grafeas.v1.SecretOccurrence" }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
