// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

public struct SlsaProvenanceZeroTwo: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  public var builder: SlsaProvenanceZeroTwo.SlsaBuilder? = nil

  public var buildType: Swift.String = Swift.String()

  public var invocation: SlsaProvenanceZeroTwo.SlsaInvocation? = nil

  public var buildConfig: GoogleCloudWkt.Struct? = nil

  public var metadata: SlsaProvenanceZeroTwo.SlsaMetadata? = nil

  public var materials: [SlsaProvenanceZeroTwo.SlsaMaterial] = []

  /// Initialize a new instance of `SlsaProvenanceZeroTwo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SlsaProvenanceZeroTwo().with { $0.builder = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Identifies the entity that executed the recipe, which is trusted to have
  /// correctly performed the operation and populated this provenance.
  public struct SlsaBuilder: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    public var id: Swift.String = Swift.String()

    /// Initialize a new instance of `SlsaBuilder`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SlsaBuilder().with { $0.id = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/grafeas.v1.SlsaProvenanceZeroTwo.SlsaBuilder"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// The collection of artifacts that influenced the build including sources,
  /// dependencies, build tools, base images, and so on.
  public struct SlsaMaterial: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    public var uri: Swift.String = Swift.String()

    public var digest: [Swift.String: Swift.String] = [:]

    /// Initialize a new instance of `SlsaMaterial`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SlsaMaterial().with { $0.uri = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/grafeas.v1.SlsaProvenanceZeroTwo.SlsaMaterial"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Identifies the event that kicked off the build.
  public struct SlsaInvocation: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    public var configSource: SlsaProvenanceZeroTwo.SlsaConfigSource? = nil

    public var parameters: GoogleCloudWkt.Struct? = nil

    public var environment: GoogleCloudWkt.Struct? = nil

    /// Initialize a new instance of `SlsaInvocation`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SlsaInvocation().with { $0.configSource = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/grafeas.v1.SlsaProvenanceZeroTwo.SlsaInvocation"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Describes where the config file that kicked off the build came from.
  /// This is effectively a pointer to the source where buildConfig came from.
  public struct SlsaConfigSource: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    public var uri: Swift.String = Swift.String()

    public var digest: [Swift.String: Swift.String] = [:]

    public var entryPoint: Swift.String = Swift.String()

    /// Initialize a new instance of `SlsaConfigSource`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SlsaConfigSource().with { $0.uri = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/grafeas.v1.SlsaProvenanceZeroTwo.SlsaConfigSource"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Other properties of the build.
  public struct SlsaMetadata: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    public var buildInvocationId: Swift.String = Swift.String()

    public var buildStartedOn: GoogleCloudWkt.Timestamp? = nil

    public var buildFinishedOn: GoogleCloudWkt.Timestamp? = nil

    public var completeness: SlsaProvenanceZeroTwo.SlsaCompleteness? = nil

    public var reproducible: Swift.Bool = Swift.Bool()

    /// Initialize a new instance of `SlsaMetadata`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SlsaMetadata().with { $0.buildInvocationId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/grafeas.v1.SlsaProvenanceZeroTwo.SlsaMetadata"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Indicates that the builder claims certain fields in this message to be
  /// complete.
  public struct SlsaCompleteness: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    public var parameters: Swift.Bool = Swift.Bool()

    public var environment: Swift.Bool = Swift.Bool()

    public var materials: Swift.Bool = Swift.Bool()

    /// Initialize a new instance of `SlsaCompleteness`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SlsaCompleteness().with { $0.parameters = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/grafeas.v1.SlsaProvenanceZeroTwo.SlsaCompleteness"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/grafeas.v1.SlsaProvenanceZeroTwo"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
