// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

public struct SlsaProvenance: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  public var builder: SlsaProvenance.SlsaBuilder? = nil

  /// Identifies the configuration used for the build.
  /// When combined with materials, this SHOULD fully describe the build,
  /// such that re-running this recipe results in bit-for-bit identical output
  /// (if the build is reproducible).
  public var recipe: SlsaProvenance.SlsaRecipe? = nil

  public var metadata: SlsaProvenance.SlsaMetadata? = nil

  /// The collection of artifacts that influenced the build including sources,
  /// dependencies, build tools, base images, and so on. This is considered to be
  /// incomplete unless metadata.completeness.materials is true. Unset or null is
  /// equivalent to empty.
  public var materials: [SlsaProvenance.Material] = []

  /// Initialize a new instance of `SlsaProvenance`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SlsaProvenance().with { $0.builder = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Steps taken to build the artifact.
  /// For a TaskRun, typically each container corresponds to one step in the
  /// recipe.
  public struct SlsaRecipe: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// URI indicating what type of recipe was performed. It determines the
    /// meaning of recipe.entryPoint, recipe.arguments, recipe.environment, and
    /// materials.
    public var type: Swift.String = Swift.String()

    /// Index in materials containing the recipe steps that are not implied by
    /// recipe.type. For example, if the recipe type were "make", then this would
    /// point to the source containing the Makefile, not the make program itself.
    /// Set to -1 if the recipe doesn't come from a material, as zero is default
    /// unset value for int64.
    public var definedInMaterial: Swift.Int64 = Swift.Int64()

    /// String identifying the entry point into the build.
    /// This is often a path to a configuration file and/or a target label within
    /// that file. The syntax and meaning are defined by recipe.type. For
    /// example, if the recipe type were "make", then this would reference the
    /// directory in which to run make as well as which target to use.
    public var entryPoint: Swift.String = Swift.String()

    /// Collection of all external inputs that influenced the build on top of
    /// recipe.definedInMaterial and recipe.entryPoint. For example, if the
    /// recipe type were "make", then this might be the flags passed to make
    /// aside from the target, which is captured in recipe.entryPoint. Depending
    /// on the recipe Type, the structure may be different.
    public var arguments: GoogleCloudWKT.`Any`? = nil

    /// Any other builder-controlled inputs necessary for correctly evaluating
    /// the recipe. Usually only needed for reproducing the build but not
    /// evaluated as part of policy. Depending on the recipe Type, the structure
    /// may be different.
    public var environment: GoogleCloudWKT.`Any`? = nil

    /// Initialize a new instance of `SlsaRecipe`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SlsaRecipe().with { $0.type = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/grafeas.v1.SlsaProvenance.SlsaRecipe"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Indicates that the builder claims certain fields in this message to be
  /// complete.
  public struct SlsaCompleteness: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// If true, the builder claims that recipe.arguments is complete, meaning
    /// that all external inputs are properly captured in the recipe.
    public var arguments: Swift.Bool = Swift.Bool()

    /// If true, the builder claims that recipe.environment is claimed to be
    /// complete.
    public var environment: Swift.Bool = Swift.Bool()

    /// If true, the builder claims that materials are complete, usually through
    /// some controls to prevent network access. Sometimes called "hermetic".
    public var materials: Swift.Bool = Swift.Bool()

    /// Initialize a new instance of `SlsaCompleteness`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SlsaCompleteness().with { $0.arguments = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/grafeas.v1.SlsaProvenance.SlsaCompleteness"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Other properties of the build.
  public struct SlsaMetadata: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Identifies the particular build invocation, which can be useful for
    /// finding associated logs or other ad-hoc analysis. The value SHOULD be
    /// globally unique, per in-toto Provenance spec.
    public var buildInvocationId: Swift.String = Swift.String()

    /// The timestamp of when the build started.
    public var buildStartedOn: GoogleCloudWKT.Timestamp? = nil

    /// The timestamp of when the build completed.
    public var buildFinishedOn: GoogleCloudWKT.Timestamp? = nil

    /// Indicates that the builder claims certain fields in this message to be
    /// complete.
    public var completeness: SlsaProvenance.SlsaCompleteness? = nil

    /// If true, the builder claims that running the recipe on materials will
    /// produce bit-for-bit identical output.
    public var reproducible: Swift.Bool = Swift.Bool()

    /// Initialize a new instance of `SlsaMetadata`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SlsaMetadata().with { $0.buildInvocationId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/grafeas.v1.SlsaProvenance.SlsaMetadata"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public struct SlsaBuilder: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    public var id: Swift.String = Swift.String()

    /// Initialize a new instance of `SlsaBuilder`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SlsaBuilder().with { $0.id = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/grafeas.v1.SlsaProvenance.SlsaBuilder"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public struct Material: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    public var uri: Swift.String = Swift.String()

    public var digest: [Swift.String: Swift.String] = [:]

    /// Initialize a new instance of `Material`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Material().with { $0.uri = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/grafeas.v1.SlsaProvenance.Material"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/grafeas.v1.SlsaProvenance"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
