// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// An Upgrade Note represents a potential upgrade of a package to a given
/// version. For each package version combination (i.e. bash 4.0, bash 4.1,
/// bash 4.1.2), there will be an Upgrade Note. For Windows, windows_update field
/// represents the information related to the update.
public struct UpgradeNote: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required for non-Windows OS. The package this Upgrade is for.
  public var `package`: Swift.String = Swift.String()

  /// Required for non-Windows OS. The version of the package in machine + human
  /// readable form.
  public var version: Version? = nil

  /// Metadata about the upgrade for each specific operating system.
  public var distributions: [UpgradeDistribution] = []

  /// Required for Windows OS. Represents the metadata about the Windows update.
  public var windowsUpdate: WindowsUpdate? = nil

  /// Initialize a new instance of `UpgradeNote`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpgradeNote().with { $0.`package` = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case `package` = "package"
    case version = "version"
    case distributions = "distributions"
    case windowsUpdate = "windowsUpdate"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.`package` = try container.decode(Swift.String.self, forKey: .`package`)
    self.version = try container.decodeIfPresent(Version.self, forKey: .version)
    self.distributions = try container.decode([UpgradeDistribution].self, forKey: .distributions)
    self.windowsUpdate = try container.decodeIfPresent(WindowsUpdate.self, forKey: .windowsUpdate)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.`package`, forKey: .`package`)
    try container.encode(self.version, forKey: .version)
    try container.encode(self.distributions, forKey: .distributions)
    try container.encode(self.windowsUpdate, forKey: .windowsUpdate)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/grafeas.v1.UpgradeNote"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
