// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// An Upgrade Occurrence represents that a specific resource_url could install a
/// specific upgrade. This presence is supplied via local sources (i.e. it is
/// present in the mirror and the running system has noticed its availability).
/// For Windows, both distribution and windows_update contain information for the
/// Windows update.
public struct UpgradeOccurrence: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required for non-Windows OS. The package this Upgrade is for.
  public var `package`: Swift.String = Swift.String()

  /// Required for non-Windows OS. The version of the package in a machine +
  /// human readable form.
  public var parsedVersion: Version? = nil

  /// Metadata about the upgrade for available for the specific operating system
  /// for the resource_url. This allows efficient filtering, as well as
  /// making it easier to use the occurrence.
  public var distribution: UpgradeDistribution? = nil

  /// Required for Windows OS. Represents the metadata about the Windows update.
  public var windowsUpdate: WindowsUpdate? = nil

  /// Initialize a new instance of `UpgradeOccurrence`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpgradeOccurrence().with { $0.`package` = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case `package` = "package"
    case parsedVersion = "parsedVersion"
    case distribution = "distribution"
    case windowsUpdate = "windowsUpdate"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.`package` = try container.decode(Swift.String.self, forKey: .`package`)
    self.parsedVersion = try container.decodeIfPresent(Version.self, forKey: .parsedVersion)
    self.distribution = try container.decodeIfPresent(
      UpgradeDistribution.self, forKey: .distribution)
    self.windowsUpdate = try container.decodeIfPresent(WindowsUpdate.self, forKey: .windowsUpdate)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.`package`, forKey: .`package`)
    try container.encode(self.parsedVersion, forKey: .parsedVersion)
    try container.encode(self.distribution, forKey: .distribution)
    try container.encode(self.windowsUpdate, forKey: .windowsUpdate)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/grafeas.v1.UpgradeOccurrence"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
