// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Windows Update represents the metadata about the update for the Windows
/// operating system. The fields in this message come from the Windows Update API
/// documented at
/// https://docs.microsoft.com/en-us/windows/win32/api/wuapi/nn-wuapi-iupdate.
public struct WindowsUpdate: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required - The unique identifier for the update.
  public var identity: WindowsUpdate.Identity? = nil

  /// The localized title of the update.
  public var title: Swift.String = Swift.String()

  /// The localized description of the update.
  public var description: Swift.String = Swift.String()

  /// The list of categories to which the update belongs.
  public var categories: [WindowsUpdate.Category] = []

  /// The Microsoft Knowledge Base article IDs that are associated with the
  /// update.
  public var kbArticleIds: [Swift.String] = []

  /// The hyperlink to the support information for the update.
  public var supportUrl: Swift.String = Swift.String()

  /// The last published timestamp of the update.
  public var lastPublishedTimestamp: GoogleCloudWkt.Timestamp? = nil

  /// Initialize a new instance of `WindowsUpdate`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = WindowsUpdate().with { $0.identity = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The unique identifier of the update.
  public struct Identity: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The revision independent identifier of the update.
    public var updateId: Swift.String = Swift.String()

    /// The revision number of the update.
    public var revision: Swift.Int32 = Swift.Int32()

    /// Initialize a new instance of `Identity`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Identity().with { $0.updateId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/grafeas.v1.WindowsUpdate.Identity"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// The category to which the update belongs.
  public struct Category: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The identifier of the category.
    public var categoryId: Swift.String = Swift.String()

    /// The localized name of the category.
    public var name: Swift.String = Swift.String()

    /// Initialize a new instance of `Category`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Category().with { $0.categoryId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/grafeas.v1.WindowsUpdate.Category"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/grafeas.v1.WindowsUpdate"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
